version: '2'
networks:
 private:
  driver: bridge
services:
 sonarqube:
    build:
      context: sonarqube/
    ports:
      - 9000:9000
      - 9092:9092
    container_name: sonarqube
  hub:
    image: "selenium/hub"
    ports:
      - 4444:4444
    networks:
      - private
  chrome:
    image: "selenium/node-chrome"
    networks:
      - private
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
